# Sidebar navigation

- label: 'Introducción'
  link: '/'
- label: Utilización
  items:
    - label: 'Tiradas de dados'
      link: '/usage/roll'
    - label: 'Ataques'
      link: '/usage/attack'
    - label: 'Tiradas de salvación'
      link: '/usage/saves'
    - label: 'Manejo de personajes'
      link: '/usage/char'
- label: Sitios de interés
  items:
    - label: 'Lierno app'
      link: https://lierno.netlify.app/
